# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 055a4464f370cb1c8815f6114d4eebe4e6bb398b0a705dca7383faecf43e92251a02aa97c189435621658e8e50b33f62eab5b1ec353d90e7a1328e98979efe16

test:
  secret_key_base: 1be2327053df2be470d59c0887bfb813611ea1c85f055a7e48d209eb3ea9cf377332bb4a6523bbfea33b4c8279ebdb534fd605630941c9d61f309cfa07c03616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
